### ISSUE TITLE
Q: Where will the particles generates?

### ISSUE THREAD

**Issue by buger404** [KennyTV/WorldEditSUI#13]
Where will the plugin generates the particles?
Will they be generated on the server, then send them to the target client through Internet?
If in this way, will this brings the server a lot burden?

Or they are just partly generated on the target client without any server transmission?

**Comment by kennytv** [comment]
They're fully server-side, hence you need to make sure to setup the config in such a way that it won't be too hard on players. There's settings regarding particle spacing, the max amount of blocks to cover and a max acceptable ping, among others you can make use of.
