### ISSUE TITLE
Large selections can trigger server crashes due to out-of-memory (OOM) errors

### ISSUE THREAD

**Issue by sgdc3** [KennyTV/WorldEditSUI#18]
It appears that a crash due to an out-of-memory (OOM) error was caused by an incorrect selection made by someone on my server. Upon reviewing the memory dump, I identified that the issue origined from memory being retained by the WESUI selection cache.
To prevent similar incidents in the future, I suggest implementing a maximum selection size limit in the configuration file.

**Comment by kennytv** [comment]
There's already `max-selection-size-to-display`, you might want to disable `enable-max-selection-bypass-perm` as well
