### ISSUE TITLE
[Enhancement] Use the Spectral outline from Mobs as the selection outline

### ISSUE THREAD

**Issue by Tsoccerguy3** [KennyTV/WorldEditSUI#3]
Still finding some lag with the particles on large edits , mostly causing network timeout .

can you use the Spectral outline to Outline a selection ? . This would be a solid line and closer to the client version lines

**Comment by kennytv** [comment]
Do you mean the glow effect given through spectral arrows for example? Cause that can only be applied to entities/players iirc. Not sure what you mean otherwise 👀

**Comment by Tsoccerguy3** [comment]
> 
> 
> Do you mean the glow effect given through spectral arrows for example? Cause that can only be applied to entities/players iirc. Not sure what you mean otherwise 👀

Yes , thats what I was thinking . Using code already in the game to draw a outline , I was hoping the spectral outline could be used to outline the blocks

**Comment by kennytv** [comment]
Hm, I don't think that is possible, as the effect can only be applied to entites, not given blocks (and any workaround would make everything worse)
