### ISSUE TITLE
Possible BukkitPlayer class definition collision?

### ISSUE THREAD

**Issue by HcNguyen111** [KennyTV/WorldEditSUI#8]
Hello,

Please see [PaperMC Issue #3137](https://github.com/PaperMC/Paper/issues/3137) to check if WorldEditSUI is in anyway related.

Thanks. (I thought it's worth a check as WorldEditSUI has WorldEdit/WorldGuard dependencies.)

**Comment by kennytv** [comment]
Made sure to not compile any of  WE's classes - the final build only contains my ones, so this shouldn't come from WESUI https://i.imgur.com/SshYdQd.png

Following the issue on Paper's tracker, no idea where it could come from tho 👀
